
package com.rpsoft.ws.greeting;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "GreetingException", targetNamespace = "http://rpsoft.com/ws/greeting/beans")
public class GreetingException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.rpsoft.ws.greeting.beans.GreetingException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GreetingException(String message, com.rpsoft.ws.greeting.beans.GreetingException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GreetingException(String message, com.rpsoft.ws.greeting.beans.GreetingException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.rpsoft.ws.greeting.beans.GreetingException
     */
    public com.rpsoft.ws.greeting.beans.GreetingException getFaultInfo() {
        return faultInfo;
    }

}
