
package com.rpsoft.ws.greeting.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.rpsoft.ws.greeting.beans.GreetingMessage;
import com.rpsoft.ws.greeting.beans.ObjectFactory;
import com.rpsoft.ws.greeting.beans.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GreetingService", targetNamespace = "http://rpsoft.com/ws/greeting/service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GreetingService {


    /**
     * 
     * @param person
     * @return
     *     returns com.rpsoft.ws.greeting.beans.GreetingMessage
     */
    @WebMethod(action = "http://rpsoft.com/ws/greeting/service/sayGoodMorning")
    @WebResult(name = "GreetingMessage", targetNamespace = "http://rpsoft.com/ws/greeting/beans", partName = "greetingMessage")
    public GreetingMessage sayGoodMorning(
        @WebParam(name = "Person", targetNamespace = "http://rpsoft.com/ws/greeting/beans", partName = "person")
        Person person);

    /**
     * 
     * @param person
     * @return
     *     returns com.rpsoft.ws.greeting.beans.GreetingMessage
     */
    @WebMethod(action = "http://rpsoft.com/ws/greeting/service/sayGoodNight")
    @WebResult(name = "GreetingMessage", targetNamespace = "http://rpsoft.com/ws/greeting/beans", partName = "greetingMessage")
    public GreetingMessage sayGoodNight(
        @WebParam(name = "Person", targetNamespace = "http://rpsoft.com/ws/greeting/beans", partName = "person")
        Person person);

}
